sudo: require
services:
  - docker
before_install:
  - docker pull node:8-onbuild

install:
  -docker build -t probot-hello .

script:
  -docker run -rm probot-hellp npm test
  -docker run -rm probot-hellp npm lint

deploy:
  provider: heroku
